import details from '../data/species-details.json';

export const POKEMON_TYPES = ['normal', 'fighting', 'flying', 'poison', 'ground', 'rock', 'bug', 'ghost', 'steel', 'fire', 'water', 'grass', 'electric', 'psychic', 'ice', 'dragon', 'dark', 'fairy'] as const;
export type PokemonType = typeof POKEMON_TYPES[number];
export type EvolutionMember = { id: number; from?: number };

// Generated by scripts/refresh-species.py: parallel arrays indexed by species id - 1.
const data = details as { types: PokemonType[]; t: number[][]; from: number[]; text: string[] };
const known = (id: number) => Number.isInteger(id) && id >= 1 && id <= data.t.length;

// Bright enough to tell apart at a glance; each color passes 4.5:1 with its text color below.
export const TYPE_COLORS: Record<PokemonType, string> = {
  normal: '#A8A77A', fighting: '#C22E28', flying: '#A98FF3', poison: '#A33EA1', ground: '#E2BF65', rock: '#B6A136',
  bug: '#A6B91A', ghost: '#735797', steel: '#B7B7CE', fire: '#F08A3C', water: '#3A6FD8', grass: '#7AC74C',
  electric: '#F7D02C', psychic: '#D23A6C', ice: '#96D9D6', dragon: '#6F35FC', dark: '#705746', fairy: '#E08DB4',
};
const INK = '#25382F'; // Matches C.ink in pokedex-ui; kept here so tests need no React Native.
function luminance(hex: string) {
  const [r, g, b] = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16) / 255).map(v => v <= .03928 ? v / 12.92 : ((v + .055) / 1.055) ** 2.4);
  return .2126 * r + .7152 * g + .0722 * b;
}
export function contrastRatio(a: string, b: string) {
  const [light, dark] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (light + .05) / (dark + .05);
}
const TYPE_TEXT = Object.fromEntries(POKEMON_TYPES.map(type => [type, contrastRatio(TYPE_COLORS[type], '#FFFFFF') >= contrastRatio(TYPE_COLORS[type], INK) ? '#FFFFFF' : INK])) as Record<PokemonType, string>;
export const typeTextColor = (type: PokemonType) => TYPE_TEXT[type];
export const typeLabel = (type: PokemonType) => type[0].toUpperCase() + type.slice(1);

export const speciesTypes = (id: number): PokemonType[] => known(id) ? data.t[id - 1].map(i => data.types[i]) : [];

// Game text wraps with newlines and page breaks; a soft or real hyphen at a wrap joins one word.
export const cleanFlavorText = (text: string) => text.replace(/­\s*/g, '').replace(/-[ \t]*[\n\f]\s*/g, '-').replace(/POKéMON/g, 'Pokémon').replace(/\s+/g, ' ').trim();
export function pokedexEntry(id: number): string | undefined {
  const text = known(id) ? cleanFlavorText(data.text[id - 1]) : '';
  return text || undefined;
}

export const evolvesFrom = (id: number) => known(id) && data.from[id - 1] ? data.from[id - 1] : undefined;
let children: Map<number, number[]> | undefined;
/** Every stage of the family containing `id`, from its first form (babies like Pichu included) to its last. Branches share a stage, grouped by parent. */
export function evolutionFamily(id: number): EvolutionMember[][] {
  if (!known(id)) return [];
  if (!children) {
    children = new Map();
    data.from.forEach((parent, i) => { if (parent) children!.set(parent, [...children!.get(parent) ?? [], i + 1]); });
  }
  let root = id;
  for (let parent = evolvesFrom(root); parent; parent = evolvesFrom(root)) root = parent;
  const grow = (stage: EvolutionMember[]) => stage.flatMap(member => (children!.get(member.id) ?? []).map(child => ({ id: child, from: member.id })));
  const stages: EvolutionMember[][] = [[{ id: root }]];
  for (let stage = grow(stages[0]); stage.length; stage = grow(stage)) stages.push(stage);
  return stages;
}

/** Discovered Pokémon per type, most common first. Dual-type Pokémon count toward both types. */
export function typeCounts(ids: Iterable<number>): { type: PokemonType; count: number }[] {
  const counts = new Map<PokemonType, number>();
  for (const id of ids) for (const type of speciesTypes(id)) counts.set(type, (counts.get(type) ?? 0) + 1);
  return POKEMON_TYPES.filter(type => counts.has(type)).map(type => ({ type, count: counts.get(type)! })).sort((a, b) => b.count - a.count);
}
